name: Publish
on:
  push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mamacrowd'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yarn berry
        run: |
          corepack enable
          yarn set version berry
          yarn config set npmScopes.mamacrowd.npmRegistryServer https://npm.pkg.github.com
          yarn config set npmScopes.mamacrowd.npmAuthToken ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - run: yarn npm publish

      - uses: actions/upload-artifact@v4
        with:
          name: yenv
          path: bundles/@yarnpkg/plugin-yenv.js
